Removed default values from flags
happy-travel/edo-contracts pull request #35
Opened 2020-11-23 11:41 UTC by DFSko

2020-11-23 11:56 UTC, mingazhev reviewed
You should up the package version. Please find how it is typically done in git. There should be at least:
- package version update
- release notes

2020-11-23 15:45 UTC, kirillta requested changes

2020-11-23 15:45 UTC, kirillta commented on HappyTravel.EdoContracts/Accommodations/Enums/BoardBasisTypes.cs
> -        NotSpecified = 0,
This must not be removed

2020-11-23 15:45 UTC, kirillta commented on HappyTravel.EdoContracts/Accommodations/Enums/LocationDescriptionCodes.cs
> -        Unspecified = 0,
This must not be removed

2020-11-23 15:45 UTC, kirillta commented on HappyTravel.EdoContracts/Accommodations/Enums/RoomTypes.cs
> -        NotSpecified = 0,
This must not be removed

2020-11-23 15:45 UTC, kirillta commented on HappyTravel.EdoContracts/Accommodations/Enums/TextualDescriptionTypes.cs
> -        Unspecified = 0,
This must not be removed

2020-11-23 15:45 UTC, kirillta commented on HappyTravel.EdoContracts/GeoData/Location.cs
> +        public Location(in GeoPoint coordinates, int distance, LocationTypes type = default)
I think the default here is not an option after changes

2020-11-23 22:14 UTC, DFSko commented on HappyTravel.EdoContracts/Accommodations/Enums/BoardBasisTypes.cs
> -        NotSpecified = 0,
Returned

2020-11-23 22:14 UTC, DFSko commented on HappyTravel.EdoContracts/Accommodations/Enums/LocationDescriptionCodes.cs
> -        Unspecified = 0,
Returned

2020-11-23 22:14 UTC, DFSko commented on HappyTravel.EdoContracts/Accommodations/Enums/RoomTypes.cs
> -        NotSpecified = 0,
Returned

2020-11-23 22:14 UTC, DFSko commented on HappyTravel.EdoContracts/Accommodations/Enums/TextualDescriptionTypes.cs
> -        Unspecified = 0,
Returned

2020-11-23 22:14 UTC, DFSko commented on HappyTravel.EdoContracts/GeoData/Location.cs
> +        public Location(in GeoPoint coordinates, int distance, LocationTypes type = default)
fixed

2020-11-23 22:14 UTC, DFSko commented
> You should up the package version. Please find how it is typically done in git. There should be at least:
> 
> * package version update
> * release notes

fixed

2020-11-23 22:54 UTC, kirillta approved these changes

2020-11-24 08:21 UTC, hasmikharutyunyan commented on HappyTravel.EdoContracts/Accommodations/Enums/PropertyTypes.cs
>      }
Flag can not have value 3

2020-11-24 08:23 UTC, hasmikharutyunyan commented on HappyTravel.EdoContracts/Accommodations/Enums/BookingStatusCodes.cs
> +        InternalProcessing = 1,
This enum is not flag

2020-11-24 09:07 UTC, DFSko commented on HappyTravel.EdoContracts/Accommodations/Enums/BookingStatusCodes.cs
> +        InternalProcessing = 1,
> This enum is not flag

Remove "Any"?

2020-11-24 09:08 UTC, DFSko commented on HappyTravel.EdoContracts/Accommodations/Enums/PropertyTypes.cs
>      }
> Flag can not have value 3

Remove "Any"?

2020-11-24 09:19 UTC, mingazhev requested changes
Changes should be only in flags

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/General/Enums/FieldTypes.cs
>      public enum FieldTypes
Is this a flag?

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/General/Enums/PassengerTitles.cs
>      [JsonConverter(typeof(StringEnumConverter))]
This is not a flag

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/General/Enums/PassengerTitles.cs
> -        [Description("")]
This is not a flag

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/General/Enums/PaymentMethods.cs
>      public enum PaymentMethods
This is not a flag

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/GeoData/Enums/LocationTypes.cs
>      public enum LocationTypes
This is not a flag

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/GeoData/Enums/PredictionSources.cs
>      public enum PredictionSources
This is not a flag

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/General/Enums/FieldTypes.cs
>      public enum FieldTypes
This is not a flag

2020-11-24 09:19 UTC, mingazhev commented on HappyTravel.EdoContracts/Accommodations/Enums/RoomTypes.cs
>          [Description("Not specified")]
This is not a flag

2020-11-24 14:44 UTC, closed without merging